#!/bin/bash
# package.sh - 将收集的dotfile打包成自解压脚本

set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly COLLECT_DIR="$SCRIPT_DIR/.collect"
readonly OUTPUT_DIR="$SCRIPT_DIR/dist"
readonly PACKAGE_NAME="dotfiles-portable"
readonly VERSION="${1:-$(date +%Y%m%d_%H%M%S)}"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${GREEN}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1" >&2; exit 1; }
info() { echo -e "${BLUE}[STEP]${NC} $1"; }

# ============================================================================
# 验证收集目录
# ============================================================================

validate_collect_dir() {
  if [ ! -d "$COLLECT_DIR" ]; then
    error "Collection directory not found. Run 'collect.sh' first"
  fi

  if [ ! -f "$COLLECT_DIR/dotfiles.txt" ]; then
    error "dotfiles.txt not found. Collection incomplete"
  fi
}

# ============================================================================
# 创建打包目录
# ============================================================================

create_package_structure() {
  info "Creating package structure..."

  rm -rf "$OUTPUT_DIR"
  mkdir -p "$OUTPUT_DIR"

  # 创建临时目录用于打包
  local pkg_temp="$OUTPUT_DIR/.pkg_temp"
  rm -rf "$pkg_temp"
  mkdir -p "$pkg_temp"/{dotfiles,packages,scripts,metadata}

  echo "$pkg_temp"
}

# ============================================================================
# 复制dotfile文件
# ============================================================================

copy_dotfiles() {
  local pkg_temp=$1
  local count=0

  info "Copying dotfiles..."

  while IFS= read -r file; do
    [ -n "$file" ] || continue
    local src="$HOME/$file"
    local dst="$pkg_temp/dotfiles/$file"

    if [ -e "$src" ] || [ -L "$src" ]; then
      mkdir -p "$(dirname "$dst")"
      cp -a "$src" "$dst"
      ((count++))
    fi
  done < "$COLLECT_DIR/dotfiles.txt"

  log "Copied $count dotfiles"
}

# ============================================================================
# 复制元数据和包列表
# ============================================================================

copy_metadata() {
  local pkg_temp=$1

  info "Copying metadata..."

  cp -r "$COLLECT_DIR/packages" "$pkg_temp/"
  cp -r "$COLLECT_DIR/metadata" "$pkg_temp/"
  cp "$COLLECT_DIR/dotfiles.txt" "$pkg_temp/metadata/"
  cp "$COLLECT_DIR/manifest.txt" "$pkg_temp/metadata/"

  log "Metadata copied"
}

# ============================================================================
# 生成安装脚本
# ============================================================================

generate_installer() {
  local pkg_temp=$1

  info "Generating installer script..."

  cat > "$pkg_temp/scripts/install.sh" << 'INSTALLER_EOF'
#!/bin/bash
# Portable Dotfile Installer
# Generated by package.sh

set -euo pipefail

readonly PKG_VERSION="__VERSION__"
readonly SCRIPT_NAME="$(basename "$0")"
readonly BACKUP_DIR="$HOME/.dotfile_backup_$(date +%Y%m%d_%H%M%S)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${GREEN}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1" >&2; exit 1; }
info() { echo -e "${BLUE}[STEP]${NC} $1"; }

# ============================================================================
# 解压数据
# ============================================================================

extract_data() {
  local extract_dir="$1"

  info "Extracting package data..."

  # 查找数据起始位置（本行之后）
  local archive_line=$(awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0;}' "$SCRIPT_NAME")

  if [ -z "$archive_line" ]; then
    error "Package data not found"
  fi

  # 解压数据
  tail -n +$archive_line "$SCRIPT_NAME" | tar xz -C "$extract_dir"

  log "Extraction complete"
}

# ============================================================================
# 备份现有文件
# ============================================================================

backup_existing_files() {
  local manifest="$1"
  local backup_count=0

  info "Checking for existing files..."

  if [ -f "$manifest" ]; then
    while IFS= read -r file; do
      [ -n "$file" ] || continue
      local target="$HOME/$file"

      if [ -e "$target" ] || [ -L "$target" ]; then
        if [ ! -d "$BACKUP_DIR" ]; then
          mkdir -p "$BACKUP_DIR"
        fi

        local backup_path="$BACKUP_DIR/$file"
        mkdir -p "$(dirname "$backup_path")"
        cp -a "$target" "$backup_path"
        ((backup_count++))
        echo "  → Backed up: $file"
      fi
    done < "$manifest"
  fi

  if [ $backup_count -gt 0 ]; then
    log "Backed up $backup_count files to: $BACKUP_DIR"
  else
    log "No existing files to backup"
  fi
}

# ============================================================================
# 安装dotfiles
# ============================================================================

install_dotfiles() {
  local src_dir="$1"
  local count=0

  info "Installing dotfiles..."

  while IFS= read -r file; do
    [ -n "$file" ] || continue
    local src="$src_dir/dotfiles/$file"
    local dst="$HOME/$file"

    if [ -e "$src" ] || [ -L "$src" ]; then
      mkdir -p "$(dirname "$dst")"
      cp -a "$src" "$dst"
      ((count++))
    fi
  done < "$src_dir/metadata/dotfiles.txt"

  log "Installed $count dotfiles"
}

# ============================================================================
# 显示包信息
# ============================================================================

show_package_info() {
  local pkg_dir="$1"

  echo ""
  echo "=========================================="
  echo "  Package Information"
  echo "=========================================="
  echo ""

  if [ -f "$pkg_dir/metadata/manifest.txt" ]; then
    head -30 "$pkg_dir/metadata/manifest.txt"
    echo "..."
    echo ""
  fi

  if [ -f "$pkg_dir/metadata/versions.txt" ]; then
    echo "=== Source System Versions ==="
    head -20 "$pkg_dir/metadata/versions.txt"
    echo ""
  fi
}

# ============================================================================
# 显示安装建议
# ============================================================================

show_install_hints() {
  echo ""
  log "Package installation hints:"
  echo ""

  if [ -d "packages" ]; then
    echo "=== System Packages ==="
    for pkg_file in packages/*.txt; do
      if [ -f "$pkg_file" ]; then
        local pm_name=$(basename "$pkg_file" .txt)
        local count=$(wc -l < "$pkg_file" 2>/dev/null || echo 0)
        echo "  $pm_name: $count packages"
        echo "  Install command: cat $pkg_file | xargs sudo apt-get install -y  # example for apt"
      fi
    done
    echo ""
  fi

  log "Next steps:"
  echo "  1. Review installed dotfiles"
  echo "  2. Install system packages from packages/ directory"
  echo "  3. Reload your shell: source ~/.zshrc"
  echo "  4. Run: dot status  # if using dotfile alias"
  echo ""

  if [ -n "${BACKUP_DIR:-}" ] && [ -d "$BACKUP_DIR" ]; then
    log "Backup location: $BACKUP_DIR"
    echo "  To restore: cp -a $BACKUP_DIR/* ~/"
  fi
}

# ============================================================================
# 主安装流程
# ============================================================================

main() {
  local mode="${1:-install}"
  local temp_dir="/tmp/dotfiles-install_$$"

  echo ""
  echo "=========================================="
  echo "  Portable Dotfile Installer"
  echo "  Version: $PKG_VERSION"
  echo "=========================================="
  echo ""

  # 清理临时目录
  trap "rm -rf $temp_dir" EXIT

  case "$mode" in
    install)
      mkdir -p "$temp_dir"

      # 解压数据
      extract_data "$temp_dir"

      # 显示包信息
      show_package_info "$temp_dir"

      # 备份现有文件
      backup_existing_files "$temp_dir/metadata/dotfiles.txt"

      # 安装dotfiles
      install_dotfiles "$temp_dir"

      echo ""
      log "✅ Installation complete!"

      show_install_hints
      ;;

    extract)
      local extract_to="${2:-./dotfiles-extracted}"
      mkdir -p "$extract_to"

      info "Extracting to: $extract_to"
      extract_data "$extract_to"

      log "Extraction complete: $extract_to"
      ;;

    info)
      mkdir -p "$temp_dir"
      extract_data "$temp_dir"
      show_package_info "$temp_dir"
      ;;

    *)
      error "Unknown mode: $mode
Usage: bash $SCRIPT_NAME [install|extract|info] [target_dir]"
      ;;
  esac
}

main "$@"
__ARCHIVE_BELOW__
INSTALLER_EOF

  # 替换版本号
  sed -i "s/__VERSION__/$VERSION/g" "$pkg_temp/scripts/install.sh"
  chmod +x "$pkg_temp/scripts/install.sh"
}

# ============================================================================
# 创建自解压包
# ============================================================================

create_self_extracting_package() {
  local pkg_temp=$1
  local output_file="$OUTPUT_DIR/${PACKAGE_NAME}-${VERSION}.sh"

  info "Creating self-extracting package..."

  # 创建tar.gz压缩包
  tar czf "$pkg_temp/data.tar.gz" -C "$pkg_temp" dotfiles packages metadata scripts

  # 合并安装脚本和数据
  cat "$pkg_temp/scripts/install.sh" "$pkg_temp/data.tar.gz" > "$output_file"
  chmod +x "$output_file"

  # 清理临时文件
  rm -rf "$pkg_temp"

  local size=$(du -h "$output_file" | cut -f1)
  log "Package created: $output_file ($size)"
}

# ============================================================================
# 生成校验和
# ============================================================================

generate_checksums() {
  local output_file="$1"

  info "Generating checksums..."

  if command -v sha256sum &> /dev/null; then
    sha256sum "$output_file" > "$output_file.sha256"
    log "SHA256: $(cat $output_file.sha256 | cut -d' ' -f1)"
  elif command -v shasum &> /dev/null; then
    shasum -a 256 "$output_file" > "$output_file.sha256"
    log "SHA256: $(cat $output_file.sha256 | cut -d' ' -f1)"
  fi
}

# ============================================================================
# 主函数
# ============================================================================

main() {
  echo ""
  echo "=========================================="
  echo "  Dotfile Packaging Tool"
  echo "=========================================="
  echo ""

  validate_collect_dir
  local pkg_temp=$(create_package_structure)
  copy_dotfiles "$pkg_temp"
  copy_metadata "$pkg_temp"
  generate_installer "$pkg_temp"
  create_self_extracting_package "$pkg_temp"

  local output_file="$OUTPUT_DIR/${PACKAGE_NAME}-${VERSION}.sh"
  generate_checksums "$output_file"

  echo ""
  log "✅ Package created successfully!"
  echo ""
  log "Package file: $output_file"
  log "Checksum file: $output_file.sha256"
  echo ""

  log "Usage on target machine:"
  echo "  # Transfer the .sh file to target machine"
  echo "  bash ${PACKAGE_NAME}-${VERSION}.sh install"
  echo ""
  echo "  # Or just extract without installing"
  echo "  bash ${PACKAGE_NAME}-${VERSION}.sh extract /path/to/extract"
  echo ""
}

main "$@"
